name: "Feature Request"
description: "Have an idea?"
title: "💡 "
labels: [enhancement, needs triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: It would greatly help us reducing duplicates and we would really appriacte if you could search the existing feature requests for the idea your about to suggest.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: A clear and concise description of what the problem is.
    placeholder: E.g. I have an issue when [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen. Add any considered drawbacks.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Teachability, Documentation, Adoption, Migration Strategy
    description: If you can, explain how users will be able to use this and benefit from it.
  validations:
    required: false
